added mongodump-command

diff --git a/commands b/commands
--- a/commands
+++ b/commands
@@ -12,17 +12,25 @@ fi
 OLDHOME=$HOME
 HOME="$DOKKU_ROOT/.mongodb"
 
+fail() {
+	echo "$@" 1>&2
+	exit 1
+}
+
+verify_min_args() {
+	local MIN_ARGS="$1"
+	[[ $# -le $((MIN_ARGS+1)) ]] && fail "Invalid number of arguments ($(($#-2)), expected $MIN_ARGS)."
+}
+
 check_exists() {
   if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
-    echo "App must exist before creating mongodb storage for it"
-    exit 1
+    fail "App must exist before creating mongodb storage for it"
   fi
 }
 
 check_app() {
   if [[ -z "$APP" ]]; then
-    echo "You must specify an app name"
-    exit 1
+    fail "You must specify an app name"
   fi
 }
 
@@ -31,17 +39,13 @@ check_db() {
   db=$(mongo $mongodb_public_ip:$mongodb_port --quiet -u admin -p"$admin_pass" --authenticationDatabase="admin" --eval "printjson(db.adminCommand('listDatabases'));" | grep name | cut -d \" -f 4 |grep -x $1)
 
   if [[ -z "$db" ]]; then
-    echo "The database $1 doesn't exist"
-    exit 1
+    fail "The database $1 doesn't exist"
   fi
-
-
 }
 
 check_container() {
   if [[ -z "$id" ]]; then
-    echo "MongoDB container not started cannot continue. Start with dokku mongodb:start"
-    exit 1
+    fail "MongoDB container not started cannot continue. Start with dokku mongodb:start"
   fi
 }
 
@@ -159,10 +163,18 @@ case "$1" in
       MONGO_URI
     ;;
   mongodb:dump)
+    verify_min_args 1 "$@"
     check_container
     check_db "$2"
 
-    echo "ejo ejo"
+    tmp_dir="/tmp/mongodump"
+    logtime=$(date +%Y-%m-%d-%Hh%Mm%Ss)
+    dumpfile="$HOME/dumps/$2-$logtime.tar.gz"
+    rm -rf "$tmp_dir"
+    mongodump -h $mongodb_public_ip --port $mongodb_port -u admin -p"$admin_pass" -d "$2" --authenticationDatabase="admin" --out "$tmp_dir" > /dev/null
+    mkdir -p "$HOME/dumps";
+    tar -zcP -C "$tmp_dir" -f "$dumpfile" "$2"
+    echo "Saved dump successfully to $dumpfile"
     ;;
   mongodb:link)
     if [[ -d "$DOKKU_ROOT/$APP" ]]; then
@@ -226,11 +238,11 @@ case "$1" in
     mongodb:console                 		    Launch an admin mongodb console
     mongodb:create <app> <database> 		    Create a Mongo database and optional params for app
     mongodb:delete <app> <database> 		    Delete specified Mongo database
-    mongodb:dump <database>		    	    Creates a binary export of the contents of a database
-    mongodb:link <app> <database>	       	    Set ENV variables for app if database exists
+    mongodb:dump <database> <filename>	   	    Creates a binary export of the contents of a database
+    mongodb:link <app> <database> 	            Set ENV variables for app if database exists
     mongodb:list                    		    List all databases
     mongodb:logs                    		    Show logs from MongoDB program
-    mongodb:restore <database>		  	    Restores the state of a database exported with mongodb:dump
+    mongodb:restore <database> <filename> 	    Restores the state of a database exported with mongodb:dump
     mongodb:start                   		    Start the MongoDB docker container if it isn't running
     mongodb:stop                    		    Stop the MongoDB docker container
     mongodb:status                  		    Shows status of MongoDB
